{
 "title": "Linkerd Authority",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(request_total{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "authority",
    "label": "Authority",
    "query": "label_values(request_total{cluster=\"$cluster\", namespace=\"$namespace\"}, authority)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"height:32px;\"/>&nbsp;\n  <span style=\"font-size: 32px\">au/$authority</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(response_total{cluster=\"$cluster\", classification=\"success\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) / sum(irate(response_total{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(request_total{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (le, authority))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>TOP-LINE TRAFFIC</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{cluster=\"$cluster\", classification=\"success\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (authority) / sum(irate(response_total{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (authority)",
     "legendFormat": "au/{{authority}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\", tls=\"true\"}[$__rate_interval])) by (authority)",
     "legendFormat": "🔒au/{{authority}}"
    },
    {
     "expr": "sum(irate(request_total{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\", tls!=\"true\"}[$__rate_interval])) by (authority)",
     "legendFormat": "au/{{authority}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (le, authority))",
     "legendFormat": "p50 au/{{authority}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (le, authority))",
     "legendFormat": "p95 au/{{authority}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (le, authority))",
     "legendFormat": "p99 au/{{authority}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC BY DEPLOYMENT</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{cluster=\"$cluster\", classification=\"success\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (deployment) / sum(irate(response_total{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\", tls=\"true\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "🔒deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\", tls!=\"true\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (le, deployment))",
     "legendFormat": "P95 deploy/{{deployment}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC BY POD</span>\n</div>"
  },
  {
   "title": "SUCCESS RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{cluster=\"$cluster\", classification=\"success\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (pod) / sum(irate(response_total{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\", tls=\"true\"}[$__rate_interval])) by (pod)",
     "legendFormat": "🔒po/{{pod}}"
    },
    {
     "expr": "sum(irate(request_total{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\", tls!=\"true\"}[$__rate_interval])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{cluster=\"$cluster\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (le, pod))",
     "legendFormat": "P95 po/{{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 33 },
   "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg\" style=\"height: 30px;\"></a>\n  </div>\n  <div id=\"version\" style=\"position: absolute; top: 0; right: 0; font-size: 15px\">\n  </div>\n</div>\n<div style=\"display:none\">\n<script type=\"text/javascript\">\nvar localReqURL =\n  window.location.href.substring(\n    0,\n    window.location.href.indexOf(\n    \"/grafana/\"\n    )\n  )+'/overview';\n\nfetch(localReqURL, {\n  credentials: 'include',\n  headers: {\n    \"Content-Type\": \"text/html; charset=utf-8\",\n  },\n})\n.then(response => response.text())\n.then(text => (new window.DOMParser()).parseFromString(text, \"text/html\"))\n.then(html => {\n  var main = html.getElementById('main');\n  var localVersion = main.getAttribute(\"data-release-version\");\n  var versionElem = document.getElementById('version');\n\n  var channel;\n  var parts = localVersion.split(\"-\", 2);\n  if (parts.length === 2) {\n    channel = parts[0];\n    versionElem.innerHTML += 'Running Linkerd ' + parts[1] + ' (' + parts[0] + ')' + '.<br>';\n  } else {\n    versionElem.innerHTML += 'Running Linkerd ' + localVersion + '.<br>';\n  }\n  var uuid = main.getAttribute(\"data-uuid\");\n\n  fetch('https://versioncheck.linkerd.io/version.json?version='+localVersion+'&uuid='+uuid+'&source=grafana', {\n    credentials: 'include',\n    headers: {\n      \"Content-Type\": \"application/json; charset=utf-8\",\n    },\n  })\n  .then(response => response.json())\n  .then(json => {\n    if (!channel || !json[channel]) {\n      versionElem.innerHTML += 'Version check failed.'\n    } else if (json[channel] === localVersion) {\n      versionElem.innerHTML += 'Linkerd is up to date.';\n    } else {\n      parts = json[channel].split(\"-\", 2);\n      if (parts.length === 2) {\n        versionElem.innerHTML += \"A new \"+parts[0]+\" version (\"+parts[1]+\") is available.\"\n      } else {\n        versionElem.innerHTML += \"A new version (\"+json[channel]+\") is available.\"\n      }\n      versionElem.innerHTML += \" <a href='https://versioncheck.linkerd.io/update' target='_blank'>Update now</a>.\";\n    }\n  });\n});\n</script>\n</div>"
  }
 ]
}