formatter: markdown table

output:
  file: README.md
  mode: inject

content: |-
  ## Example

  ```hcl
  {{ include "examples/main.tf" }}
  ```

  {{ .Requirements }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

settings:
  hide-empty: true
