{
 "title": "RabbitMQ Queues Overview",
 "description": "Rabbitmq stats using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   },
   {
    "name": "RabbitMQ",
    "query": {
     "query": "label_values(rabbitmq_version_info{cluster=\"$Cluster\"}, rabbitmq_cluster)"
    }
   },
   {
    "name": "Queue",
    "query": {
     "query": "label_values(rabbitmq_queue_messages{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"}, queue)"
    }
   }
  ]
 },
 "panels": [
  { "title": "rabbitmq_cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Channels / Connections / Consumers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(rabbitmq_channels{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"})",
     "legendFormat": "Channels"
    },
    {
     "expr": "max(rabbitmq_connections{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"})",
     "legendFormat": "Connections"
    },
    {
     "expr": "max(rabbitmq_consumers{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"})",
     "legendFormat": "Consumers"
    }
   ]
  },
  {
   "title": "Consumers by Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (queue) (rabbitmq_queue_consumers{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "description": "unacked - Number of messages delivered to clients but not yet acknowledged.\n\nready - Number of messages ready to be delivered to clients.\n\ntotal - Number ready and unacknowledged messages in rabbitmq_cluster.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacknowledged_global{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"})",
     "legendFormat": "unacked"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_ready_global{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"})\n",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_global{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Messages Throughput",
   "type": "timeseries",
   "description": "published - messages published\n\ndeliver - messages delivered in acknowledgement mode to consumers.\n\ndeliver no-ack - messages delivered in no-acknowledgement mode to consumers.\nacknowledgements.\n\nredelivered - messages in deliver_get which had the redelivered flag set.\n\nreturned - messages returned to publisher as unroutable.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_queue_messages_delivered_noack_total{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"}[1m]))",
     "legendFormat": "deliver no-ack"
    },
    {
     "expr": "sum(rate(rabbitmq_queue_messages_delivered_total{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"}[1m]))",
     "legendFormat": "deliver"
    },
    {
     "expr": "sum(rate(rabbitmq_queue_messages_redelivered_total{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"}[1m]))",
     "legendFormat": "redelivered"
    },
    {
     "expr": "sum(rate(rabbitmq_queue_messages_published_total{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"}[1m]))",
     "legendFormat": "published"
    },
    {
     "expr": "sum(rate(rabbitmq_queue_messages_returned_total{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\"}[1m]))",
     "legendFormat": "returned"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Messages $Queue",
   "type": "timeseries",
   "description": "unacked - Number of messages delivered to clients but not yet acknowledged.\n\nready - Number of messages ready to be delivered to clients.\n\ntotal - Number ready and unacknowledged messages in rabbitmq_cluster.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "repeat": "Queue",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacknowledged{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\", queue=\"$Queue\"})",
     "legendFormat": "unacked"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_ready{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\", queue=\"$Queue\"})\n",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(rabbitmq_queue_messages{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\", queue=\"$Queue\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Consumers $Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "repeat": "Queue",
   "targets": [
    {
     "expr": "sum by (queue) (rabbitmq_queue_consumers{cluster=\"$Cluster\", rabbitmq_cluster=\"$RabbitMQ\", queue=\"$Queue\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}