{
 "title": "Cert manager",
 "description": "Monitors cert-manager resources",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(exported_namespace)"
    }
   },
   {
    "name": "Certificate",
    "query": {
     "query": "label_values(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$Namespace\"},name) "
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Soonest Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(certmanager_certificate_expiration_timestamp_seconds{name=~\"$Certificate\",exported_namespace=~\"$Namespace\", cluster=~\"$Cluster\"} > 0) - time()"
    }
   ]
  },
  {
   "title": "Certificates Ready",
   "type": "stat",
   "description": "The number of certificates in the ready state.",
   "gridPos": { "h": 7, "w": 12, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status{name=~\"$Certificate\",exported_namespace=~\"$Namespace\", cluster=~\"$Cluster\"}) by(condition) ",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_http_acme_client_request_count)"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time Left",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sort_desc( sum(certmanager_certificate_expiration_timestamp_seconds{name=~\"$Certificate\",exported_namespace=~\"$Namespace\", cluster=~\"$Cluster\"} - time()) by(name,exported_namespace) )",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "Certificate Ready Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status{name=~\"$Certificate\",exported_namespace=~\"$Namespace\", cluster=~\"$Cluster\"}) by(condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_expiration_timestamp_seconds{name=~\"$Certificate\",exported_namespace=~\"$Namespace\", cluster=~\"$Cluster\"} - time()) by(name,exported_namespace, cluster)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ACME Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ACME HTTP Request avg duration",
   "type": "timeseries",
   "description": "Average duration of requests to ACME provider. ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, path, status) (rate(certmanager_http_acme_client_request_duration_seconds_sum[$__rate_interval]))\n/\nsum by (method, path, status) (rate(certmanager_http_acme_client_request_duration_seconds_count[$__rate_interval]))\nor on() vector(0)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "ACME HTTP Requests/sec",
   "type": "timeseries",
   "description": "Rate of requests to ACME provider.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, path, status) (\n  rate(certmanager_http_acme_client_request_count[2m])\n) or on() vector(0)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Controller Sync Requests/sec",
   "type": "timeseries",
   "description": "The rate of controller sync requests.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (controller) (\n  rate(certmanager_controller_sync_call_count[$__rate_interval])\n)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "ACME Client Request Paths",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "/directory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/directory\"}[2m])) by(status) or on() vector(0)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/cert",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/cert\"}[2m])) by(status) or on() vector(0)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/new-acct",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/new-acct\"}[2m])) by(status) or on() vector(0)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/order",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/order\"}[2m])) by(status) or on() vector(0)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/new-order",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/new-order\"}[2m])) by(status) or on() vector(0)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/authz-v3",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/authz-v3\"}[2m])) by(status) or on() vector(0)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/chall-v3",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/chall-v3\"}[2m])) by(status) or on() vector(0)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/finalize",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/finalize\"}[2m])) by(status) or on() vector(0)",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  }
 ]
}