{
 "title": "Containers",
 "description": "Detailed Containers metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$Cluster\"},namespace)"
    }
   },
   {
    "name": "Pods",
    "label": "Pod group",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$Cluster\", namespace=\"$Namespace\"}, pod)"
    }
   },
   {
    "name": "Containers",
    "query": {
     "query": "label_values(kube_pod_container_status_running{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "CPU usage of all selected containers in cores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "stat",
   "description": "CPU requests of all selected containers in cores",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "stat",
   "description": "CPU limits of all selected containers in cores",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    }
   ]
  },
  {
   "title": "MEM usage",
   "type": "stat",
   "description": "MEM wss usage of all selected containers in bytes",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    }
   ]
  },
  {
   "title": "MEM requests",
   "type": "stat",
   "description": "MEM requests of all selected containers in bytes",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    }
   ]
  },
  {
   "title": "MEM limits",
   "type": "stat",
   "description": "MEM limits of all selected containers in bytes",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "description": "Number of all selected containers in running state",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    }
   ]
  },
  {
   "title": "Waiting",
   "type": "stat",
   "description": "Number of all selected containers in waiting state",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "description": "Number of restarts for all selected containers",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    }
   ]
  },
  {
   "title": "Container states",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container state",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (pod, container)(kube_pod_container_status_ready{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    },
    {
     "expr": "sum by (pod, container)(kube_pod_container_status_running{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    },
    {
     "expr": "sum by (pod, container)(kube_pod_container_status_waiting{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    },
    {
     "expr": "sum by (pod, container)(kube_pod_container_status_restarts_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    },
    {
     "expr": "sum by (pod, container)(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    },
    {
     "expr": "sum by (pod, container)(kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    },
    {
     "expr": "sum by (pod, container)(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    },
    {
     "expr": "sum by (pod, container)(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage containers",
   "type": "timeseries",
   "description": "CPU usage per selected container type in cores",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m]))",
     "legendFormat": "{{container}} - usage"
    }
   ]
  },
  {
   "title": "CPU usage total",
   "type": "timeseries",
   "description": "CPU usage of all selected containers in cores",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m]))",
     "legendFormat": "total - usage"
    }
   ]
  },
  {
   "title": "CPU CFS containers",
   "type": "timeseries",
   "description": "CPU CFS stats per selected container type in CFS period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (container)(rate(container_cpu_cfs_periods_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m]))",
     "legendFormat": "{{container}} -  total"
    },
    {
     "expr": "sum by (container)(rate(container_cpu_cfs_throttled_periods_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m]))",
     "legendFormat": "{{container}} - throttled"
    }
   ]
  },
  {
   "title": "CPU CFS total",
   "type": "timeseries",
   "description": "CPU CFS stats of all selected containers in CFS period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_periods_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m]))",
     "legendFormat": "throttled"
    }
   ]
  },
  {
   "title": "CPU per Container [%]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage per Container [%]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "repeat": "Containers",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m])) by (pod,container) * 100 / scalar(max(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}))",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage per Container [cores]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage per Container",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
     "repeat": "Containers",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m])",
       "legendFormat": "{{ pod }}/{{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Mem WSS total",
     "type": "timeseries",
     "description": "MEM WSS (working set size) usage usage of all selected containers in bytes. WSS is the total physical memory (RAM) used by the process, this also includes memory-mapped files and various other resources,",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})",
       "legendFormat": "wss total"
      }
     ]
    },
    {
     "title": "Mem usage",
     "type": "timeseries",
     "description": "MEM usage per selected container type in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (container)(container_memory_usage_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})",
       "legendFormat": "{{container}} - usage"
      }
     ]
    },
    {
     "title": "Mem  max usage",
     "type": "timeseries",
     "description": "MEM max usage per selected container type in bytes. Max usage is maximum memory usage recorded in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (container)(container_memory_max_usage_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})",
       "legendFormat": "{{container}} - max usage"
      }
     ]
    },
    {
     "title": "Mem WSS usage",
     "type": "timeseries",
     "description": "MEM WSS (working set size) per selected container type in bytes. WSS is the total physical memory (RAM) used by the process, this also includes memory-mapped files and various other resources,",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (container)(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})",
       "legendFormat": "{{container}} - wss"
      }
     ]
    },
    {
     "title": "Mem cached",
     "type": "timeseries",
     "description": "MEM cached per selected container type in bytes.\nCached is number of bytes of page cache memory.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (container)(container_memory_cache{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})",
       "legendFormat": "{{container}} - cached"
      }
     ]
    },
    {
     "title": "Mem RSS",
     "type": "timeseries",
     "description": "MEM RSS usage per selected container type in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (container)(container_memory_rss{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})",
       "legendFormat": "{{container}} - rss"
      }
     ]
    },
    {
     "title": "Mem fail count",
     "type": "timeseries",
     "description": "MEM fail count per selected container type in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (container)(container_memory_failcnt{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"})",
       "legendFormat": "{{container}} - fail count"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory per Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
     "repeat": "Containers",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}",
       "legendFormat": "{{ pod }}/ {{ container }} "
      },
      {
       "expr": "scalar(max(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}))",
       "legendFormat": "limits"
      },
      {
       "expr": "scalar(max(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}))",
       "legendFormat": "requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory per Container [%]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory usage [%]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
     "repeat": "Containers",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}) * 100 / scalar(max(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}))",
       "legendFormat": "{{pod}}/{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Filesystem Bandwith",
     "type": "timeseries",
     "description": "Bandwith per selected container type in bytes/s",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(container)(irate(container_fs_reads_bytes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m]))",
       "legendFormat": "{{ container }} - read"
      },
      {
       "expr": "sum by(container)(irate(container_fs_write_bytes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m]))",
       "legendFormat": "{{ container }} - write"
      }
     ]
    },
    {
     "title": "Filesystem Throughput",
     "type": "timeseries",
     "description": "Bandwith per selected container type in bytes/s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by(container)(irate(container_fs_reads_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m]))",
       "legendFormat": "{{ container }} - read"
      },
      {
       "expr": "sum by(container)(irate(container_fs_writes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"($Pods).+\", container=~\"($Containers)\"}[2m]))",
       "legendFormat": "{{ container }} - write"
      }
     ]
    }
   ]
  }
 ]
}