{
 "title": "Ingress Controller Overview (Nginx)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster=\"$Cluster\"},controller_namespace)"
    }
   },
   {
    "name": "ControllerClass",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster=\"$Cluster\", controller_namespace=\"$Namespace\"}, controller_class) "
    }
   },
   {
    "name": "Controller",
    "label": "Controller (Pod)",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\"}, controller_pod) "
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\"}, controller_pod) "
    }
   },
   {
    "name": "Deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_pod_owner{cluster=\"$Cluster\", namespace=\"$Namespace\",pod=\"$Pod\"},owner_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Desired Pods",
   "type": "stat",
   "description": "Displays the desired number of replicas of the application, which you define when you create the Deployment. This is the desired state.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{cluster=\"$Cluster\",namespace=\"$Namespace\",deployment=\"$Deployment\"}"
    }
   ]
  },
  {
   "title": "Current Pods",
   "type": "stat",
   "description": "Displays how many replicas are currently running",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{cluster=\"$Cluster\",namespace=\"$Namespace\",deployment=\"$Deployment\"}"
    }
   ]
  },
  {
   "title": "Available Pods",
   "type": "stat",
   "description": "Displays how many replicas of the application are available to your users.",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{cluster=\"$Cluster\",namespace=\"$Namespace\",deployment=\"$Deployment\"}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "stat",
   "description": "Displays summary of all container restarts in given interval",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(kube_pod_container_status_restarts_total{cluster=\"$Cluster\",namespace=\"$Namespace\",pod=~\"$Deployment.+\"}[$__range])) - sum(min_over_time(kube_pod_container_status_restarts_total{cluster=\"$Cluster\",namespace=\"$Namespace\",pod=~\"$Deployment.+\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pending Deployment",
   "type": "stat",
   "description": "Pending changes on the deployment",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_metadata_generation{cluster=\"$Cluster\",namespace=\"$Namespace\",deployment=\"$Deployment\"} - kube_deployment_status_observed_generation{cluster=\"$Cluster\",namespace=\"$Namespace\",deployment=\"$Deployment\"}"
    }
   ]
  },
  {
   "title": "Last Deployment",
   "type": "stat",
   "description": "How old is deployment",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - min(container_start_time_seconds{cluster=\"$Cluster\",namespace=\"$Namespace\",pod=~\"$Deployment.+\"})"
    }
   ]
  },
  {
   "title": "CPU Usage (deployment)",
   "type": "timeseries",
   "description": "Displays CPU average usage in cores per deployment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"}[1m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"}[1m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"}[1m]))",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Mem Usage (deployment)",
   "type": "timeseries",
   "description": "Displays Mem average usage in bytes per pod.\n\nWSS/OOM:\nThe amount of working set memory, this includes recently accessed memory,dirty memory, and kernel memory.\n\nUsage:\nCurrent memory usage, this includes all memory regardless of when it was accessed.\n\nRSS:\nThe amount of anonymous and swap cache memory, includes transparent hugepages). Real memory pages that are currently mapped.\n\nCache:\nNumber of bytes of page cache memory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"})",
     "legendFormat": "WSS/OOM"
    }
   ]
  },
  {
   "title": "Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Rate by Controller",
     "type": "timeseries",
     "description": "Displays requests per second by controller",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}[1m])) by (controller_pod)",
       "legendFormat": "{{ controller_pod }}"
      },
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Connections by Controller",
     "type": "timeseries",
     "description": "Displays connections per second by controller",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "conn/s" } },
     "yaxes": [
      { "format": "short", "label": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_nginx_process_connections_total{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}[1m])) by (controller_pod)",
       "legendFormat": "{{ controller_pod }}"
      },
      {
       "expr": "sum(rate(nginx_ingress_controller_nginx_process_connections_total{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Request Bandwidth by Controller",
     "type": "timeseries",
     "description": "Displays the requests length (including request line, header, and request body) per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_size_sum{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}[1m])) by (controller_pod)",
       "legendFormat": "{{ controller_pod }}"
      },
      {
       "expr": "sum(rate(nginx_ingress_controller_request_size_sum{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Response Bandwidth by Controller",
     "type": "timeseries",
     "description": "Displays the response length (including request line, header, and request body) per second",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_response_size_sum{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}[1m])) by (controller_pod)",
       "legendFormat": "{{ controller_pod }}"
      },
      {
       "expr": "sum(rate(nginx_ingress_controller_response_size_sum{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Controller State",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(nginx_ingress_controller_config_last_reload_successful{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}) by (controller_pod)"
      },
      {
       "expr": "max(nginx_ingress_controller_config_last_reload_successful_timestamp_seconds{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}) by (controller_pod) * 1000"
      },
      {
       "expr": "max(nginx_ingress_controller_success{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}) by (controller_pod)"
      },
      {
       "expr": "max(nginx_ingress_controller_nginx_process_num_procs{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}) by (controller_pod)"
      },
      {
       "expr": "max(nginx_ingress_controller_nginx_process_connections_total{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}) by (controller_pod)"
      },
      {
       "expr": "max(nginx_ingress_controller_nginx_process_requests_total{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\"}) by (controller_pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Rate by Ingress",
     "type": "timeseries",
     "description": "Displays requests per second by controller",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\", ingress!=\"\"}[1m])) by (ingress)",
       "legendFormat": "{{ ingress }}"
      }
     ]
    },
    {
     "title": "Request Error Rate by Ingress",
     "type": "timeseries",
     "description": "Displays percentage comparing total requests with 5xx",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\", ingress!=\"\" ,status=~\"[5][0-9][0-9]\"}[1m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\", ingress!=\"\"}[1m])) by (ingress)",
       "legendFormat": "{{ ingress }}"
      }
     ]
    },
    {
     "title": "Request Bandwidth by Ingress",
     "type": "timeseries",
     "description": "Displays the requests length (including request line, header, and request body) per second",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_size_sum{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\", ingress!=\"\"}[1m])) by (ingress)",
       "legendFormat": "{{ ingress }}"
      }
     ]
    },
    {
     "title": "Response Bandwidth by Ingress",
     "type": "timeseries",
     "description": "Displays the response length (including request line, header, and request body) per second",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_response_size_sum{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\", ingress!=\"\"}[1m])) by (ingress)",
       "legendFormat": "{{ ingress }}"
      },
      {
       "expr": "sum(rate(nginx_ingress_controller_response_size_sum{cluster=\"$Cluster\", controller_namespace=\"$Namespace\",controller_class=\"$ControllerClass\", controller_pod=~\"$Controller\", ingress!=\"\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Ingress Certificate Expiry",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "min(nginx_ingress_controller_ssl_expire_time_seconds{cluster=\"$Cluster\",namespace=~\"$Namespace\", pod=~\"$Controller\"}) by (host) - time()",
       "legendFormat": "{{ host }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage (pod)",
     "type": "timeseries",
     "description": "Displays CPU average usage in cores per pod",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} usage"
      },
      {
       "expr": "sum(rate(container_cpu_system_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} system"
      },
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} user"
      }
     ]
    },
    {
     "title": "CPU Usage (pod/container)",
     "type": "timeseries",
     "description": "Displays CPU average usage in cores per pod and container",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\", container!=\"\"}[1m])) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }}  usage"
      }
     ]
    },
    {
     "title": "CPU Requests/Limits",
     "type": "table",
     "description": "Displays Requests  and/or Limits per container\n\nGuaranteed QoS: \nEvery Container in the Pod must have a memory limit and a memory request, and they must be the same.Every Container in the Pod must have a CPU limit and a CPU request, and they must be the same.\n\nBurstable Qos:\nThe Pod does not meet the criteria for QoS class Guaranteed.At least one Container in the Pod has a memory or CPU request\n\nBestEffort QoS:\nPod must not have any memory or CPU limits or requests.",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(label_join(kube_pod_container_resource_requests_cpu_cores{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}, \"pod_container\", \"/\", \"pod\", \"container\")) by (pod_container) or on() vector(-1)"
      },
      {
       "expr": "max(label_join(kube_pod_container_resource_limits_cpu_cores{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}, \"pod_container\", \"/\", \"pod\", \"container\")) by (pod_container) or on() vector(-1)"
      }
     ]
    },
    {
     "title": "CPU Throttled (pod/container)",
     "type": "timeseries",
     "description": "Displays Throttled CPU  in cores per pod and container when container is in Guaranteed QoS",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"}[1m])) by (pod, container) or on() vector(0)",
       "legendFormat": "{{ pod }}/{{container}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Mem Usage (pod)",
     "type": "timeseries",
     "description": "Displays Mem average usage in bytes per pod.\n\nWSS/OOM:\nThe amount of working set memory, this includes recently accessed memory,dirty memory, and kernel memory.\n\nUsage:\nCurrent memory usage, this includes all memory regardless of when it was accessed.\n\nRSS:\nThe amount of anonymous and swap cache memory, includes transparent hugepages). Real memory pages that are currently mapped.\n\nCache:\nNumber of bytes of page cache memory.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"}) by (pod)",
       "legendFormat": "{{ pod }} usage"
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"}) by (pod)",
       "legendFormat": "{{ pod }} RSS"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"}) by (pod)",
       "legendFormat": "{{ pod }} WSS/OOM"
      }
     ]
    },
    {
     "title": "Mem Usage (pod/container)",
     "type": "timeseries",
     "description": "Displays Mem average usage in bytes per pod and container.\n\nWSS/OOM:\nThe amount of working set memory, this includes recently accessed memory,dirty memory, and kernel memory.\n\nUsage:\nCurrent memory usage, this includes all memory regardless of when it was accessed.\n\nRSS:\nThe amount of anonymous and swap cache memory, includes transparent hugepages). Real memory pages that are currently mapped.\n\nCache:\nNumber of bytes of page cache memory.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\", container!=\"\"}) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} WSS/OOM"
      },
      {
       "expr": "sum(container_memory_usage_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\", container!=\"\"}) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} usage"
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\", container!=\"\"}) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} RSS"
      },
      {
       "expr": "sum(container_memory_cache{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\", container!=\"\"}) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} cache"
      }
     ]
    },
    {
     "title": "Mem Requests/Limits",
     "type": "table",
     "description": "Displays Requests  and/or Limits per container\n\nGuaranteed QoS: \nEvery Container in the Pod must have a memory limit and a memory request, and they must be the same.Every Container in the Pod must have a CPU limit and a CPU request, and they must be the same.\n\nBurstable Qos:\nThe Pod does not meet the criteria for QoS class Guaranteed.At least one Container in the Pod has a memory or CPU request\n\nBestEffort QoS:\nPod must not have any memory or CPU limits or requests.",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(label_join(kube_pod_container_resource_requests_mem_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}, \"pod_container\", \"/\", \"pod\", \"container\")) by (pod_container) or on() vector(-1)"
      },
      {
       "expr": "max(label_join(kube_pod_container_resource_limits_mem_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}, \"pod_container\", \"/\", \"pod\", \"container\")) by (pod_container) or on() vector(-1)"
      }
     ]
    },
    {
     "title": "Memory Failures",
     "type": "timeseries",
     "description": "Displays number of memory usage hits limits",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "failures" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_memory_failcnt{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\", container!~\"(POD|)\"}[1m])) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} IN"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}[1m])) by (pod)",
       "legendFormat": "{{ pod}} OUT"
      }
     ]
    },
    {
     "title": "Network Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} IN"
      },
      {
       "expr": "sum(rate(container_network_transmit_errors_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} OUT"
      }
     ]
    },
    {
     "title": "Network Packet Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} IN"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}[1m])) by (pod)",
       "legendFormat": "{{ pod}} OUT"
      }
     ]
    },
    {
     "title": "Network Packet Drop Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} IN"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\"}[1m])) by (pod)",
       "legendFormat": "{{ pod}} OUT"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "FS Throughput (pod/container)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", container!~\"(POD|)\"}[1m])) by (pod, container) or on() vector(0)",
       "legendFormat": "{{ pod }}/{{ container }} Read"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", container!~\"(POD|)\"}[1m])) by (pod, container) or on() vector(0)",
       "legendFormat": "{{ pod }}/{{ container }} Write"
      }
     ]
    }
   ]
  }
 ]
}