{
 "title": "DaemonSets",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_daemonset_created{cluster=\"$Cluster\"},namespace)"
    }
   },
   {
    "name": "DaemonSet",
    "query": {
     "query": "label_values(kube_daemonset_created{cluster=\"$Cluster\",namespace=\"$Namespace\"},daemonset)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_ready{cluster=\"$Cluster\",namespace=\"$Namespace\",daemonset=\"$DaemonSet\"}"
    }
   ]
  },
  {
   "title": "Available Pods",
   "type": "stat",
   "description": "Displays how many replicas are currently running",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{cluster=\"$Cluster\",namespace=\"$Namespace\",daemonset=\"$DaemonSet\"}"
    }
   ]
  },
  {
   "title": "Unavailable Pods",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_unavailable{cluster=\"$Cluster\",namespace=\"$Namespace\",daemonset=\"$DaemonSet\"}"
    }
   ]
  },
  {
   "title": "Misscheduled Pods",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_misscheduled{cluster=\"$Cluster\",namespace=\"$Namespace\",daemonset=\"$DaemonSet\"}"
    }
   ]
  },
  {
   "title": "CPU Usage (damonset)",
   "type": "timeseries",
   "description": "Displays CPU average usage in cores per daemonset",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\"}[2m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\"}[2m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\"}[2m]))",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Mem Usage (daemonset)",
   "type": "timeseries",
   "description": "Displays Mem average usage in bytes per pod.\n\nWSS/OOM:\nThe amount of working set memory, this includes recently accessed memory,dirty memory, and kernel memory.\n\nUsage:\nCurrent memory usage, this includes all memory regardless of when it was accessed.\n\nRSS:\nThe amount of anonymous and swap cache memory, includes transparent hugepages). Real memory pages that are currently mapped.\n\nCache:\nNumber of bytes of page cache memory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\"})",
     "legendFormat": "WSS/OOM"
    }
   ]
  },
  {
   "title": "Pod events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total container restarts",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "max(kube_pod_container_status_restarts_total{pod=~\"$DaemonSet.+\", namespace=\"$Namespace\"} )by (pod, container)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage (pod)",
     "type": "timeseries",
     "description": "Displays CPU average usage in cores per pod",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\", container!=\"\"}[2m])) by (pod)",
       "legendFormat": "{{ pod }} usage"
      },
      {
       "expr": "sum(rate(container_cpu_system_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\", container!=\"\"}[2m])) by (pod)",
       "legendFormat": "{{ pod }} system"
      },
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\", container!=\"\"}[2m])) by (pod)",
       "legendFormat": "{{ pod }} user"
      }
     ]
    },
    {
     "title": "CPU Usage (pod/container)",
     "type": "timeseries",
     "description": "Displays CPU average usage in cores per pod and container",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", container!=\"\", image!~\".+pause.+\"}[2m])) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }}  usage"
      }
     ]
    },
    {
     "title": "CPU Requests/Limits",
     "type": "table",
     "description": "Displays Requests  and/or Limits per container\n\nGuaranteed QoS: \nEvery Container in the Pod must have a memory limit and a memory request, and they must be the same.Every Container in the Pod must have a CPU limit and a CPU request, and they must be the same.\n\nBurstable Qos:\nThe Pod does not meet the criteria for QoS class Guaranteed.At least one Container in the Pod has a memory or CPU request\n\nBestEffort QoS:\nPod must not have any memory or CPU limits or requests.",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(label_join(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}, \"pod_container\", \"/\", \"pod\", \"container\")) by (pod_container) or on() vector(-1)"
      },
      {
       "expr": "max(label_join(kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}, \"pod_container\", \"/\", \"pod\", \"container\")) by (pod_container) or on() vector(-1)"
      }
     ]
    },
    {
     "title": "CPU Throttled (pod/container)",
     "type": "timeseries",
     "description": "Displays Throttled CPU  in cores per pod and container when container is in Guaranteed QoS",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\"}[2m])) by (pod, container) or on() vector(0)",
       "legendFormat": "{{ pod }}/{{container}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Mem Usage (pod)",
     "type": "timeseries",
     "description": "Displays Mem average usage in bytes per pod.\n\nWSS/OOM:\nThe amount of working set memory, this includes recently accessed memory,dirty memory, and kernel memory.\n\nUsage:\nCurrent memory usage, this includes all memory regardless of when it was accessed.\n\nRSS:\nThe amount of anonymous and swap cache memory, includes transparent hugepages). Real memory pages that are currently mapped.\n\nCache:\nNumber of bytes of page cache memory.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\"}) by (pod)",
       "legendFormat": "{{ pod }} usage"
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$Deployment.+\", image!~\".+pause.+\"}) by (pod)",
       "legendFormat": "{{ pod }} RSS"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\"}) by (pod)",
       "legendFormat": "{{ pod }} WSS/OOM"
      }
     ]
    },
    {
     "title": "Mem Usage (pod/container)",
     "type": "timeseries",
     "description": "Displays Mem average usage in bytes per pod and container.\n\nWSS/OOM:\nThe amount of working set memory, this includes recently accessed memory,dirty memory, and kernel memory.\n\nUsage:\nCurrent memory usage, this includes all memory regardless of when it was accessed.\n\nRSS:\nThe amount of anonymous and swap cache memory, includes transparent hugepages). Real memory pages that are currently mapped.\n\nCache:\nNumber of bytes of page cache memory.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", container!=\"\", image!~\".+pause.+\"}) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} WSS/OOM"
      },
      {
       "expr": "sum(container_memory_usage_bytes{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", container!=\"\", image!~\".+pause.+\"}) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} usage"
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", container!=\"\", image!~\".+pause.+\"}) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} RSS"
      },
      {
       "expr": "sum(container_memory_cache{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", container!=\"\", image!~\".+pause.+\"}) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} cache"
      }
     ]
    },
    {
     "title": "Mem Requests/Limits",
     "type": "table",
     "description": "Displays Requests  and/or Limits per container\n\nGuaranteed QoS: \nEvery Container in the Pod must have a memory limit and a memory request, and they must be the same.Every Container in the Pod must have a CPU limit and a CPU request, and they must be the same.\n\nBurstable Qos:\nThe Pod does not meet the criteria for QoS class Guaranteed.At least one Container in the Pod has a memory or CPU request\n\nBestEffort QoS:\nPod must not have any memory or CPU limits or requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(label_join(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}, \"pod_container\", \"/\", \"pod\", \"container\")) by (pod_container) or on() vector(-1)"
      },
      {
       "expr": "max(label_join(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}, \"pod_container\", \"/\", \"pod\", \"container\")) by (pod_container) or on() vector(-1)"
      }
     ]
    },
    {
     "title": "Memory Failures",
     "type": "timeseries",
     "description": "Displays number of memory usage hits limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_memory_failcnt{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", image!~\".+pause.+\"}[2m])) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Throughput",
     "type": "timeseries",
     "description": "If pods of this DaemonSet have host network enabled, the graph represents the network traffic of the host\n\nCheck it in Cluster node > Network PODs",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}[2m])) by (pod)",
       "legendFormat": "{{ pod }} IN"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}[2m])) by (pod)",
       "legendFormat": "{{ pod}} OUT"
      }
     ]
    },
    {
     "title": "Network Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}[2m])) by (pod)",
       "legendFormat": "{{ pod }} IN"
      },
      {
       "expr": "sum(rate(container_network_transmit_errors_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}[2m])) by (pod)",
       "legendFormat": "{{ pod }} OUT"
      }
     ]
    },
    {
     "title": "Network Packet Rate",
     "type": "timeseries",
     "description": "If pods of this DaemonSet have host network enabled, the graph represents the network traffic of the host\n\nCheck it in Cluster node > Network PODs",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}[2m])) by (pod)",
       "legendFormat": "{{ pod }} IN"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}[2m])) by (pod)",
       "legendFormat": "{{ pod}} OUT"
      }
     ]
    },
    {
     "title": "Network Packet Drop Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}[2m])) by (pod)",
       "legendFormat": "{{ pod }} IN"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\"}[2m])) by (pod)",
       "legendFormat": "{{ pod}} OUT"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "FS I/O (pod/container)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", container!=\"POD\"}[2m])) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} Read"
      },
      {
       "expr": "sum(rate(container_fs_writes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", container!=\"POD\"}[2m])) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} Write"
      }
     ]
    },
    {
     "title": "FS Throughput (pod/container)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", container!=\"POD\"}[2m])) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} Read"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$Cluster\", namespace=\"$Namespace\", pod=~\"$DaemonSet.+\", container!=\"POD\"}[2m])) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }} Write"
      }
     ]
    }
   ]
  }
 ]
}