{
 "title": "Namespaces Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ready pods",
   "type": "stat",
   "description": "Total number of ready pods in all namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Running\"} == 1) and on(namespace, pod) (kube_pod_status_ready{cluster=\"$Cluster\", condition=\"true\"} == 1))"
    }
   ]
  },
  {
   "title": "Unready pods",
   "type": "stat",
   "description": "Total not ready in all namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Running\"} == 1) and on(namespace, pod) (kube_pod_status_ready{cluster=\"$Cluster\", condition=\"true\"} == 0)) or vector(0)"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "stat",
   "description": "Total number of pending pods in all namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Pending\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Ready containers",
   "type": "stat",
   "description": "Total number of ready containers in all namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_container_status_running{cluster=\"$Cluster\"} == 1) and on(namespace, pod, container) (kube_pod_container_status_ready{cluster=\"$Cluster\"} == 1))"
    }
   ]
  },
  {
   "title": "Unready containers",
   "type": "stat",
   "description": "Total number of  unready containers in all namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_container_status_running{cluster=\"$Cluster\"} == 1) and on(namespace, pod, container) (kube_pod_container_status_ready{cluster=\"$Cluster\"} == 0)) or vector(0)"
    }
   ]
  },
  {
   "title": "Pending containers",
   "type": "stat",
   "description": "Total number of pending containers in all namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{cluster=\"$Cluster\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "CPU usage in all namespaces in cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", container!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "stat",
   "description": "CPU requests in all namespaces in cores",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "stat",
   "description": "CPU limits in all namespaces in cores",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "Memory wss usage in all namespaces in bytes",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "stat",
   "description": "Memory requests in all namespaces in bytes",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "description": "Memory limits in all namespaces in bytes",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Namespace status",
   "type": "table",
   "description": "Namespace status by namespace",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count by (namespace)((kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Running\"} == 1) and on(namespace, pod) (kube_pod_status_ready{cluster=\"$Cluster\", condition=\"true\"} == 1))\n"
    },
    {
     "expr": "count by(namespace)((kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Running\"} == 1) and on(namespace, pod) (kube_pod_status_ready{cluster=\"$Cluster\", condition=\"true\"} == 0)) or vector(0)\n"
    },
    {
     "expr": "count by(namespace)(kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Pending\"} == 1) or vector(0)\n"
    },
    {
     "expr": "sum by(namespace)(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", container!=\"\"}[2m]))\n"
    },
    {
     "expr": "sum by(namespace)(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", container!=\"\"})\n"
    },
    {
     "expr": "sum by(namespace)(kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", container!=\"\"})\n"
    },
    {
     "expr": "sum by(namespace)(container_memory_working_set_bytes{cluster=\"$Cluster\", container!=\"\"})\n"
    },
    {
     "expr": "sum by(namespace)(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", container!=\"\"})\n"
    },
    {
     "expr": "sum by(namespace)(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "CPU usage per  namespace in cores",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "targets": [
      {
       "expr": "sum by(namespace)(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", container!=\"\"}[2m]))\n",
       "legendFormat": "{{ namespace }} - usage"
      }
     ]
    },
    {
     "title": "TOP Pod CPU Usage",
     "type": "table",
     "description": "TOP CPU usage per namespace/pod in cores",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum by (namespace, pod)(rate(container_cpu_user_seconds_total{cluster=\"$Cluster\", container!='', container!=\"POD\"}[2m]))))"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory usage",
     "type": "timeseries",
     "description": "Memory wss usage per namespace in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(namespace)(container_memory_working_set_bytes{cluster=\"$Cluster\", container!=\"\"})\n",
       "legendFormat": "{{ namespace }} - usage"
      }
     ]
    },
    {
     "title": "TOP Pod Memory Usage",
     "type": "table",
     "description": "TOP Pod Memory wss usage per namespace/pod in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(container_memory_working_set_bytes{cluster=\"$Cluster\", container!='', container!=\"POD\"}) by (namespace, pod)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Bandwidth",
     "type": "timeseries",
     "description": "Network bandwidth  per namespace in bytes/sec\n\nIf pods in the Namespace have host network enabled, the graph represents the network traffic of the host\n\nCheck it in Cluster node > Network PODs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(namespace)(rate(container_network_receive_bytes_total{cluster=\"$Cluster\",pod!=\"\"}[2m])) + sum by(namespace)(rate(container_network_transmit_bytes_total{cluster=\"$Cluster\",pod!=\"\"}[2m]))",
       "legendFormat": "{{ namespace }} - bandwidth"
      }
     ]
    },
    {
     "title": "TOP Pod Network Bandwith",
     "type": "table",
     "description": "TOP Pod network bandwith per namespace/pod in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(rate(container_network_receive_bytes_total{cluster=\"$Cluster\", pod!=''}[2m])) by (namespace, pod) + sum(rate(container_network_transmit_bytes_total{cluster=\"$Cluster\", pod!=''}[2m])) by (namespace, pod)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Filesystem Throughput",
     "type": "timeseries",
     "description": "Filesystem throughput per namespace in bytes/sec",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$Cluster\", container!=''}[2m])) by (namespace) + sum(rate(container_fs_writes_bytes_total{cluster=\"$Cluster\", container!=''}[2m])) by (namespace)",
       "legendFormat": "{{ namespace }} - throughput"
      }
     ]
    },
    {
     "title": "TOP Pod Filesystem Throughput",
     "type": "table",
     "description": "TOP Pod filesystem throughput per namespace/pod in bytes/sec",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(rate(container_fs_reads_bytes_total{cluster=\"$Cluster\", container!=''}[2m])) by (namespace, pod) + sum(rate(container_fs_writes_bytes_total{cluster=\"$Cluster\", container!=''}[2m])) by (namespace, pod)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ready pods",
     "type": "timeseries",
     "description": "Ready pods per namespace in # of pods",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(namespace)((kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Running\"} == 1) and on(namespace, pod) (kube_pod_status_ready{cluster=\"$Cluster\", condition=\"true\"} == 1))",
       "legendFormat": "{{ namespace }} - ready"
      }
     ]
    },
    {
     "title": "Unready / Pending pods",
     "type": "timeseries",
     "description": "Unready / Pending pods per namespace in # of pods",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(namespace)((kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Running\"} == 1) and on(namespace, pod) (kube_pod_status_ready{cluster=\"$Cluster\", condition=\"true\"} == 0)) or vector(0)",
       "legendFormat": "{{ namespace }} - unready"
      },
      {
       "expr": "count by(namespace)(kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Pending\"} == 1) or vector(0)",
       "legendFormat": "{{ namespace }} - pending"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ready containers",
     "type": "timeseries",
     "description": "Ready containers per namespace in # of pods",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(namespace)((kube_pod_container_status_running{cluster=\"$Cluster\"} == 1) and on(namespace, pod, container) (kube_pod_container_status_ready{cluster=\"$Cluster\"} == 1))",
       "legendFormat": "{{ namespace }} - ready"
      }
     ]
    },
    {
     "title": "Unready / Pending containers",
     "type": "timeseries",
     "description": "Unready / Pending containers per namespace in # of pods",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(namespace)((kube_pod_container_status_running{cluster=\"$Cluster\"} == 1) and on(namespace, pod, container) (kube_pod_container_status_ready{cluster=\"$Cluster\"} == 0)) or vector(0)",
       "legendFormat": "{{ namespace }} - unready"
      },
      {
       "expr": "count by(namespace)(kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Pending\"} == 1) or vector(0)",
       "legendFormat": "{{ namespace }} - pending"
      }
     ]
    },
    {
     "title": "Container Restarts",
     "type": "timeseries",
     "description": "Pods restarts per namespace in # of restarts",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(changes(kube_pod_container_status_restarts_total{cluster=\"$Cluster\"}[2m])) by (namespace)",
       "legendFormat": "{{ namespace }} - #  restarts"
      }
     ]
    },
    {
     "title": "TOP POD Container Restarts",
     "type": "table",
     "description": "TOP POD Container restarts per namespace/pod  in # of restarts",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(kube_pod_container_status_restarts_total{cluster=\"$Cluster\"}) by (namespace, pod) > 0))"
      }
     ]
    }
   ]
  }
 ]
}