{
 "title": "Namespace",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=\"$Cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ready pods",
   "type": "stat",
   "description": "Total number of ready pods in selected namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_status_phase{cluster=\"$Cluster\", namespace=~\"$Namespace\", phase=\"Running\"} == 1) and on(namespace, pod) (kube_pod_status_ready{cluster=\"$Cluster\",namespace=~\"$Namespace\", condition=\"true\"} == 1)) or vector(0)"
    }
   ]
  },
  {
   "title": "Unready pods",
   "type": "stat",
   "description": "Total not ready in selected namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_status_phase{cluster=\"$Cluster\", namespace=~\"$Namespace\", phase=\"Running\"} == 1) and on(namespace, pod) (kube_pod_status_ready{cluster=\"$Cluster\", namespace=~\"$Namespace\", condition=\"true\"} == 0)) or vector(0)"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "stat",
   "description": "Total number of pending pods in selected namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{cluster=\"$Cluster\", namespace=~\"$Namespace\", phase=\"Pending\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Ready containers",
   "type": "stat",
   "description": "Total number of ready containers in selected namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_container_status_running{cluster=\"$Cluster\", namespace=~\"$Namespace\"} == 1) and on(namespace, pod, container) (kube_pod_container_status_ready{cluster=\"$Cluster\", namespace=~\"$Namespace\"} == 1)) or vector(0)"
    }
   ]
  },
  {
   "title": "Unready containers",
   "type": "stat",
   "description": "Total number of  unready containers in selected namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_container_status_running{cluster=\"$Cluster\", namespace=~\"$Namespace\"} == 1) and on(namespace, pod, container) (kube_pod_container_status_ready{cluster=\"$Cluster\", namespace=~\"$Namespace\"} == 0)) or vector(0)"
    }
   ]
  },
  {
   "title": "Pending containers",
   "type": "stat",
   "description": "Total number of pending containers in selected namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{cluster=\"$Cluster\", namespace=~\"$Namespace\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "CPU usage in selected namespaces in cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}[2m])) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "stat",
   "description": "CPU requests in selected namespaces in cores",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "stat",
   "description": "CPU limits in selected namespaces in cores",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "Memory wss usage in all selected in bytes",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "stat",
   "description": "Memory requests in selected namespaces in bytes",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "description": "Memory limits in selected namespaces in bytes",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Limits / Quotas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Resource Quotas",
     "type": "table",
     "description": "ResourceQuotas are for limiting the total resource consumption in a whole namespace",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_resourcequota{cluster=\"$Cluster\", namespace=~\"$Namespace\"}  or on() vector(-1)"
      }
     ]
    },
    {
     "title": "Limit Ranges",
     "type": "table",
     "description": "Limit Ranges in selected namespaces:\n\nLimit Ranges are for managing constraints at a pod and container level",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_limitrange{cluster=\"$Cluster\", namespace=~\"$Namespace\"} or on() vector(-1)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage / Requests Total",
     "type": "timeseries",
     "description": "CPU total usage of pods in selected namespaces in cores",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}[2m]))",
       "legendFormat": "usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}) or vector(0)",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "CPU usage of pods in selected namespaces in cores",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "targets": [
      {
       "expr": "sum by (namespace, pod)(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}[2m]))",
       "legendFormat": "{{namespace}}/{{pod}} - usage"
      }
     ]
    },
    {
     "title": "TOP Pod CPU Usage",
     "type": "table",
     "description": "TOP CPU usage per namespace/pod in cores",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum by (namespace, pod)(rate(container_cpu_user_seconds_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!='', container!=\"POD\"}[2m]))))"
      }
     ]
    },
    {
     "title": "CPU throttled",
     "type": "timeseries",
     "description": "CPU throttled time of pods in selected namespaces in cores",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "targets": [
      {
       "expr": "sum by (namespace, pod)(rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}[2m]))",
       "legendFormat": "{{namespace}}/{{pod}} - throttled"
      }
     ]
    },
    {
     "title": "TOP Pod CPU Throttled",
     "type": "table",
     "description": "TOP CPU throttled per namespace/pod in cores",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum by (namespace, pod)(rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!='', container!=\"POD\"}[2m]))))"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory WSS / Requests total",
     "type": "timeseries",
     "description": "MEM wss total usage of pods in selected namespaces in cores.\n\nMEM WSS (working set size) usage usage of all selected containers in bytes. WSS is the total physical memory (RAM) used by the process, this also includes memory-mapped files and various other resources,",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"})",
       "legendFormat": "usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}) or vector(0)",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "description": "Memory wss usage  of pods in selected namespaces in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(namespace, pod)(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"})\n",
       "legendFormat": "{{ namespace }}/{{ pod}} - used"
      }
     ]
    },
    {
     "title": "TOP Pod Memory Usage",
     "type": "table",
     "description": "TOP Pod Memory wss usage per namespace/pod in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(container_memory_working_set_bytes{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!='', container!=\"POD\"}) by (namespace, pod)))"
      }
     ]
    },
    {
     "title": "Memory cache",
     "type": "timeseries",
     "description": "Memory cache usage of pods in selected namespaces  in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(namespace, pod)(container_memory_cache{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"})\n",
       "legendFormat": "{{ namespace }}/{{ pod}} - cached"
      }
     ]
    },
    {
     "title": "TOP Pod Memory Cache",
     "type": "table",
     "description": "TOP Pod Memory wss usage per namespace/pod in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(container_memory_cache{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}) by (namespace, pod)))"
      }
     ]
    },
    {
     "title": "Memory Max Usage",
     "type": "timeseries",
     "description": "Memory maximum of pods in selected namespaces  in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(namespace, pod)(container_memory_max_usage_bytes{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"})\n",
       "legendFormat": "{{ namespace }}/{{ pod}} - max usage"
      }
     ]
    },
    {
     "title": "TOP Pod Memory Max Usage",
     "type": "table",
     "description": "TOP Pod Memory max usage per namespace/pod in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(container_memory_max_usage_bytes{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}) by (namespace, pod)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Bandwidth",
     "type": "timeseries",
     "description": "Network bandwidth  per namespace/pod in bytes/sec\n\nIf the pod has host network enabled, the graph represents the network traffic of the host\n\nCheck it in Cluster node > Network PODs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(namespace, pod)(rate(container_network_receive_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", pod!=\"\"}[2m])) + sum by(namespace, pod)(rate(container_network_transmit_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", pod!=\"\"}[2m]))",
       "legendFormat": "{{ namespace }}/{{ pod }} - bandwidth"
      }
     ]
    },
    {
     "title": "TOP Pod Network Bandwith",
     "type": "table",
     "description": "TOP Pod network bandwith per namespace/pod in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(rate(container_network_receive_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", pod!=''}[2m])) by (namespace, pod) + sum(rate(container_network_transmit_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", pod!=''}[2m])) by (namespace, pod)))"
      }
     ]
    },
    {
     "title": "Network Receive Bandwidth",
     "type": "timeseries",
     "description": "Network receive bandwidth  of pods in selected namespaces  in bytes/sec\n\nIf the pod has host network enabled, the graph represents the network traffic of the host\n\nCheck it in Cluster node > Network PODs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(namespace, pod)(rate(container_network_receive_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", pod!=\"\"}[2m]))",
       "legendFormat": "{{ namespace }}/{{ pod }} - receive bandwidth"
      }
     ]
    },
    {
     "title": "TOP Pod Network Receive Bandwith",
     "type": "table",
     "description": "TOP Pod network receive bandwith per namespace/pod in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(rate(container_network_receive_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", pod!=''}[2m])) by (namespace, pod)))"
      }
     ]
    },
    {
     "title": "Network Transmit Bandwidth",
     "type": "timeseries",
     "description": "Network transmit bandwidth  of pods in selected namespaces  in bytes/sec\n\nIf the pod has host network enabled, the graph represents the network traffic of the host\n\nCheck it in Cluster node > Network PODs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(namespace, pod)(rate(container_network_transmit_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", pod!=\"\"}[2m]))",
       "legendFormat": "{{ namespace }}/{{ pod }} - transmit bandwidth"
      }
     ]
    },
    {
     "title": "TOP Pod Network Transmit Bandwith",
     "type": "table",
     "description": "TOP Pod network transmit bandwith per namespace/pod in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(rate(container_network_transmit_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", pod!=''}[2m])) by (namespace, pod)))"
      }
     ]
    },
    {
     "title": "Network Packets dropped",
     "type": "timeseries",
     "description": "Network packets dropped of pods in selected namespaces   in pps\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by(pod)(rate(container_network_receive_packets_dropped_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", pod!=\"\"}[2m])) + sum by(pod)(rate(container_network_transmit_packets_dropped_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", pod!=\"\"}[2m]))",
       "legendFormat": "{{ namespace }}/{{ pod }} - dropped"
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "timeseries",
     "description": "Network errors of pods in selected namespaces  type as # errors",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "err/s" } },
     "targets": [
      {
       "expr": "sum by(pod)(rate(container_network_receive_errors_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", pod!=\"\"}[2m])) + sum by(pod)(rate(container_network_transmit_errors_total{cluster=\"$Cluster\", namespace=~\"$Namespace\",pod!=\"\"}[1m]))",
       "legendFormat": "{{ namespace }}{{ pod }} - errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Filesystem Throughput",
     "type": "timeseries",
     "description": "Filesystem throughput of pods in selected namespaces  in bytes/s",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(namespace, pod)(rate(container_fs_writes_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}[2m])) + sum by(namespace, pod)(rate(container_fs_reads_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}[2m]))",
       "legendFormat": "{{ namespace }}/{{ pod }} - throughput"
      }
     ]
    },
    {
     "title": "TOP Pod Filesystem Throughput",
     "type": "table",
     "description": "TOP Pod filesystem throughput per namespace/pod in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(rate(container_fs_writes_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=''}[2m])) by (namespace, pod) + sum(rate(container_fs_reads_bytes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=''}[2m])) by (namespace, pod)))"
      }
     ]
    },
    {
     "title": "Filesystem IOPS",
     "type": "timeseries",
     "description": "Filesystem IOPS of pods in selected namespaces  in bytes/s",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by(namespace, pod)(rate(container_fs_reads_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}[2m])) + sum by(namespace, pod)(rate(container_fs_writes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=\"\"}[2m]))",
       "legendFormat": "{{ namespace }}/{{ pod }} - iops"
      }
     ]
    },
    {
     "title": "TOP Pod Filesystem IOPS",
     "type": "table",
     "description": "TOP Pod filesystem IOPS per namespace/pod in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(rate(container_fs_writes_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=''}[2m])) by (namespace, pod) + sum(rate(container_fs_reads_total{cluster=\"$Cluster\", namespace=~\"$Namespace\", container!=''}[2m])) by (namespace, pod)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ready pods",
     "type": "timeseries",
     "description": "Ready pods in selected namespaces in # of pods",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(namespace)((kube_pod_status_phase{cluster=\"$Cluster\", namespace=~\"$Namespace\", phase=\"Running\"} == 1) and on(namespace, pod) (kube_pod_status_ready{cluster=\"$Cluster\", namespace=~\"$Namespace\", condition=\"true\"} == 1))",
       "legendFormat": "{{ namespace }} - ready"
      }
     ]
    },
    {
     "title": "Unready / Pending pods",
     "type": "timeseries",
     "description": "Unready / Pending pods in selected namespace in # of pods",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(namespace)((kube_pod_status_phase{cluster=\"$Cluster\", namespace=~\"$Namespace\", phase=\"Running\"} == 1) and on(namespace, pod) (kube_pod_status_ready{cluster=\"$Cluster\", namespace=~\"$Namespace\", condition=\"true\"} == 0)) or vector(0)",
       "legendFormat": "{{ namespace }} - unready"
      },
      {
       "expr": "count by(namespace)(kube_pod_status_phase{cluster=\"$Cluster\", namespace=~\"$Namespace\", phase=\"Pending\"} == 1) or vector(0)",
       "legendFormat": "{{ namespace }} - pending"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ready containers",
     "type": "timeseries",
     "description": "Ready containers in selected namespaces in # of pods",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(namespace)((kube_pod_container_status_running{cluster=\"$Cluster\", namespace=~\"$Namespace\"} == 1) and on(namespace, pod, container) (kube_pod_container_status_ready{cluster=\"$Cluster\", namespace=~\"$Namespace\"} == 1))",
       "legendFormat": "{{ namespace }} - ready"
      }
     ]
    },
    {
     "title": "Unready / Pending containers",
     "type": "timeseries",
     "description": "Unready / Pending containers per namespace in # of pods",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(namespace)((kube_pod_container_status_running{cluster=\"$Cluster\", namespace=~\"$Namespace\"} == 1) and on(namespace, pod, container) (kube_pod_container_status_ready{cluster=\"$Cluster\", namespace=~\"$Namespace\"} == 0)) or vector(0)",
       "legendFormat": "{{ namespace }} - unready"
      },
      {
       "expr": "count by(namespace)(kube_pod_status_phase{cluster=\"$Cluster\", namespace=~\"$Namespace\", phase=\"Pending\"} == 1) or vector(0)",
       "legendFormat": "{{ namespace }} - pending"
      }
     ]
    },
    {
     "title": "Container Restarts",
     "type": "timeseries",
     "description": "Pods restarts per namespace in # of restarts",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(changes(kube_pod_container_status_restarts_total{cluster=\"$Cluster\", namespace=~\"$Namespace\"}[2m])) by (namespace)",
       "legendFormat": "{{ namespace }} - #  restarts"
      }
     ]
    },
    {
     "title": "TOP POD Container Restarts",
     "type": "table",
     "description": "TOP POD Container restarts per namespace/pod  in # of restarts",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum(kube_pod_container_status_restarts_total{cluster=\"$Cluster\", namespace=~\"$Namespace\"}) by (namespace, pod) > 0))"
      }
     ]
    }
   ]
  }
 ]
}