{
 "title": "Cluster Nodes Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Worker Node count",
   "type": "stat",
   "description": "Number of worker nodes in cluster",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=\"$Cluster\", label_kubernetes_io_role!=\"master\"})"
    }
   ]
  },
  {
   "title": "CPU cores total",
   "type": "stat",
   "description": "Total CPU cores in cluster",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Allocatable CPU cores",
   "type": "stat",
   "description": "Total Allocatable CPU cores of all nodes",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "CPU usage of all nodes",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", container!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "stat",
   "description": "CPU requests in all namespaces in cores",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "stat",
   "description": "Total Memory in cluster",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Allocatable Memory",
   "type": "stat",
   "description": "Allocatable Memory of all nodes",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "Memory wss usage in all namespaces in bytes",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "stat",
   "description": "Memory requests in all namespaces in bytes",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage in cluster",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$Cluster\", mode=\"system\"}[2m]))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$Cluster\", mode='user'}[2m]))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$Cluster\", mode='iowait'}[2m]))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$Cluster\", mode!~'iowait|user|system'}[2m]))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage in cluster",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\",container!=\"\"})",
     "legendFormat": "used"
    },
    {
     "expr": "(sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\"}) - sum(container_memory_working_set_bytes{cluster=\"$Cluster\",container!=\"\"}))",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Instance status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node)(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\"})",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum by (node)(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\"})",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum by (node)(kube_node_spec_unschedulable{cluster=\"$Cluster\"})",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "count by(node)(kube_pod_info{cluster=\"$Cluster\"})",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Conditions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node Condition",
     "type": "timeseries",
     "description": "Displays node condition\n1 - condition is true\n0 - condition is false",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_node_status_condition{cluster=\"$Cluster\", condition=\"Ready\", status=\"true\"}",
       "legendFormat": "{{ node }} - Ready"
      },
      {
       "expr": "kube_node_status_condition{cluster=\"$Cluster\", condition=\"OutOfDisk\", status=\"true\"}",
       "legendFormat": "{{ node }} - OutOfDisk"
      },
      {
       "expr": "kube_node_status_condition{cluster=\"$Cluster\", condition=\"MemoryPressure\", status=\"true\"}",
       "legendFormat": "{{ node }} - MemoryPressure"
      },
      {
       "expr": "kube_node_status_condition{cluster=\"$Cluster\", condition=\"PIDPressure\", status=\"true\"}",
       "legendFormat": "{{ node }} - PIDPressure"
      },
      {
       "expr": "kube_node_status_condition{cluster=\"$Cluster\", condition=\"DiskPressure\", status=\"true\"}",
       "legendFormat": "{{ node }} - DiskPressure"
      }
     ]
    },
    {
     "title": "Node Problem Detector Monitors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "problem_gauge{cluster=\"$Cluster\"}",
       "legendFormat": "{{node}}/{{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU load",
     "type": "timeseries",
     "description": "CPU load in cluster by instance in percent",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (instance_name)(node_load1{cluster=\"$Cluster\"}) / count by (instance_name)(node_cpu_seconds_total{cluster=\"$Cluster\", mode='idle'}) * 100",
       "legendFormat": "{{ instance_name }}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "CPU usage in cluster by instance in cores",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance_name)(rate(node_cpu_seconds_total{mode!=\"idle\", cluster=\"$Cluster\"}[2m])) ",
       "legendFormat": "{{ instance_name }} - usage"
      }
     ]
    },
    {
     "title": "TOP Pod CPU Usage",
     "type": "table",
     "description": "TOP 5 Pod CPU usage per instance  in cores.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "topk by(node)(5, sort_desc(sum by (node, pod)(rate(container_cpu_user_seconds_total{cluster=\"$Cluster\", container!='', container!=\"POD\"}[2m]))))",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory usage",
     "type": "timeseries",
     "description": "Memory usage in cluster by instance in bytes",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(instance)(container_memory_working_set_bytes{cluster=\"$Cluster\", container!='', container!=\"POD\"})",
       "legendFormat": "{{ instance }} - usage"
      }
     ]
    },
    {
     "title": "TOP Pod Memory Usage",
     "type": "table",
     "description": "TOP 5 Pod Memory usage per instance in cores.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk by(node)(5, sort_desc(sum(container_memory_working_set_bytes{cluster=\"$Cluster\", container!='', container!=\"POD\"}) by (pod, node)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Bandwidth",
     "type": "timeseries",
     "description": "Network bandwidth of non-host network pods per instance in bytes/sec",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(node)(rate(container_network_receive_bytes_total{cluster=\"$Cluster\",pod!=\"\", id!=\"\"}[1m]) * on(pod) group_left() (count by (pod)(container_network_receive_bytes_total{interface=~\"eth.+\"}) == 1)) + sum by(node)(rate(container_network_transmit_bytes_total{cluster=\"$Cluster\",pod!=\"\", id!=\"\"}[1m]) * on(pod) group_left() (count by (pod)(container_network_transmit_bytes_total{interface=~\"eth.+\"}) == 1))",
       "legendFormat": "{{node}} - bandwidth (pods)"
      }
     ]
    },
    {
     "title": "TOP Non-Host Pod Network Bandwidth",
     "type": "table",
     "description": "TOP 5 Non-Host Pod network bandwidth per instance in bytes/sec.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk by(node)(5, sort_desc(sum(rate(container_network_receive_bytes_total{cluster=\"$Cluster\", pod!=''}[2m]) * on(pod) group_left() (count by (pod)(container_network_transmit_bytes_total{interface=~\"eth.+\"}) == 1)) by (node, pod) + sum(rate(container_network_transmit_bytes_total{cluster=\"$Cluster\", pod!=''}[1m]) * on(pod) group_left() (count by (pod)(container_network_transmit_bytes_total{interface=~\"eth.+\"}) == 1)) by (node, pod)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Filesystem Throughput",
     "type": "timeseries",
     "description": "Filesystem throughput per instance in bytes/sec",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$Cluster\", container!=''}[2m])) by (instance) + sum(rate(container_fs_writes_bytes_total{cluster=\"$Cluster\", container!=''}[2m])) by (instance)",
       "legendFormat": "{{ instance }} - throughput"
      }
     ]
    },
    {
     "title": "TOP Pod Filesystem Throughput",
     "type": "table",
     "description": "TOP Pod filesystem throughput per namespace/pod in bytes/sec",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk by(node)(5, sort_desc(sum(rate(container_fs_reads_bytes_total{cluster=\"$Cluster\", container!=''}[2m])) by (node, pod) + sum(rate(container_fs_writes_bytes_total{cluster=\"$Cluster\", container!=''}[2m])) by (node, pod)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Timex",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Timex offset seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_time_zone_offset_seconds{cluster=\"$Cluster\",job=\"node-exporter\"}",
       "legendFormat": "{{instance_name}}"
      }
     ]
    }
   ]
  }
 ]
}