{
 "title": "Container Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Displays total CPU usage of all containers",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\",container!=\"\"}[2m]))",
     "legendFormat": "usage"
    },
    {
     "expr": " sum(rate(container_cpu_user_seconds_total{cluster=\"$Cluster\",container!=\"\"}[2m]))",
     "legendFormat": "user"
    },
    {
     "expr": " sum(rate(container_cpu_system_seconds_total{cluster=\"$Cluster\",container!=\"\"}[2m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$Cluster\",container!=\"\"}[2m]))",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Displays sum of memory usage of all containers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{cluster=\"$Cluster\",container!=\"\"})",
     "legendFormat": "cache"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$Cluster\",container!=\"\"})",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\",container!=\"\"})",
     "legendFormat": "working_set"
    },
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$Cluster\",container!=\"\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "FS Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$Cluster\",container!=\"\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$Cluster\",container!=\"\"}[2m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "TOP Container restarts",
   "type": "table",
   "description": "Displays the number of container restarts for TOP 10 containers with 1 or more restarts",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(kube_pod_container_status_restarts_total{cluster=\"$Cluster\"} > 0))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "CPU usage per container",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", container!=\"\"}[2m])) by (pod, container)",
       "legendFormat": "{{ pod}}/{{ container }}"
      }
     ]
    },
    {
     "title": "TOP CPU Usage",
     "type": "table",
     "description": "Displays CPU usage for TOP 10 containers",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sort_desc(sum by (container, pod)(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", container!=\"\"}[2m]))))"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "description": "Displays amount of CPU throttling per container",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$Cluster\", container!=\"\"}[2m])) by (pod, container)",
       "legendFormat": "{{ pod }}/{{ container }}"
      }
     ]
    },
    {
     "title": "TOP CPU Throttling",
     "type": "table",
     "description": "Displays CPU throttling for TOP 10 containers",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sort_desc(topk(10, sum(rate(container_cpu_cfs_throttled_seconds_total{container!=\"\"}[2m])) by (container, pod)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Displays memory usage and working sets per container",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (pod, container) (container_memory_working_set_bytes{cluster=\"$Cluster\", container!=\"\"})",
       "legendFormat": "{{ pod }}/{{ container }} working set"
      }
     ]
    },
    {
     "title": "TOP Memory usage",
     "type": "table",
     "description": "Displays memory usage and working sets for TOP 20",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sort_desc(sum by (container, pod) (container_memory_usage_bytes{cluster=\"$Cluster\", container!=\"\"})))"
      },
      {
       "expr": "topk(20, sort_desc(sum by (container, pod) (container_memory_working_set_bytes{cluster=\"$Cluster\", container!=\"\"})))"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "FS Throughput",
     "type": "timeseries",
     "description": "Displays combined throughput (read+write) per container",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (pod, container) (rate(container_fs_writes_bytes_total{cluster=\"$Cluster\", container!=\"\", container!=\"POD\"}[2m])) +  sum by (pod, container) (rate(container_fs_reads_bytes_total{cluster=\"$Cluster\", container!=\"\", container!=\"POD\"}[2m]))",
       "legendFormat": "{{ pod }}/{{ container }}"
      }
     ]
    },
    {
     "title": "FS Throughput",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (container, pod) (rate(container_fs_reads_bytes_total{cluster=\"$Cluster\", container!=\"\"}[2m]))"
      },
      {
       "expr": "sum by (container, pod) (rate(container_fs_writes_bytes_total{cluster=\"$Cluster\", container!=\"\"}[2m])) "
      }
     ]
    }
   ]
  }
 ]
}