{
 "title": "Cluster Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", id=~\"/kubepods(.slice)?\"}[2m])) / sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Allocatable CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\", cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", id=~\"/kubepods(.slice)?\"}) / sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Containers Allocatable Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\", cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{cluster=\"$Cluster\", id=\"/\"}) / sum(container_fs_limit_bytes{cluster=\"$Cluster\", id=\"/\", kubernetes_io_hostname!=\"master\"}) * 100"
    }
   ]
  },
  {
   "title": "Containers Allocatable Filesystem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{cluster=\"$Cluster\", id=\"/\", kubernetes_io_hostname!=\"master\"})"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$Cluster\", id=~\"/kubepods(.slice)?\"}[2m]))"
    }
   ]
  },
  {
   "title": "Container Memory usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$Cluster\", id=~\"/kubepods(.slice)?\"})"
    }
   ]
  },
  {
   "title": "Containers Filesystem usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{cluster=\"$Cluster\", id=\"/\"})"
    }
   ]
  },
  {
   "title": "Hosts CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$Cluster\", mode!=\"idle\"}[2m])) / sum(machine_cpu_cores{cluster=\"$Cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Hosts CPU cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Hosts Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{cluster=\"$Cluster\"}) - sum(node_memory_MemFree_bytes{cluster=\"$Cluster\"}) - sum(node_memory_Buffers_bytes{cluster=\"$Cluster\"}) - sum(node_memory_Cached_bytes{cluster=\"$Cluster\"})) / sum(node_memory_MemTotal_bytes{cluster=\"$Cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Hosts Allocatable Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Hosts Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{cluster=\"$Cluster\"}) - sum(node_filesystem_free_bytes{cluster=\"$Cluster\"})) / sum(node_filesystem_size_bytes{cluster=\"$Cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Hosts  Filesystem size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Hosts CPU usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$Cluster\", mode!=\"idle\"}[2m]))"
    }
   ]
  },
  {
   "title": "Hosts Memory usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$Cluster\"}) - sum(node_memory_MemFree_bytes{cluster=\"$Cluster\"}) - sum(node_memory_Buffers_bytes{cluster=\"$Cluster\"}) - sum(node_memory_Cached_bytes{cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Hosts Filesystem usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$Cluster\"}) - sum(node_filesystem_free_bytes{cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance_name)(node_load1{cluster=\"$Cluster\"})",
     "legendFormat": "{{ instance_name }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$Cluster\", mode=\"system\"}[2m]))",
     "legendFormat": "System"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$Cluster\", mode='user'}[2m]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$Cluster\", mode='iowait'}[2m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$Cluster\", mode!~'iowait|user|system'}[2m]))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(node)(container_memory_working_set_bytes{cluster=\"$Cluster\", id=\"/\"})",
     "legendFormat": "{{ node }} - usage"
    }
   ]
  },
  {
   "title": "Network Traffic Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{cluster=\"$Cluster\"}[2m])) by (instance_name) + sum(irate(node_network_transmit_bytes_total{cluster=\"$Cluster\"}[2m])) by (instance_name)",
     "legendFormat": "{{instance_name}} - bandwidth"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Nodes - Ready",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"Ready\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Worker Node count",
     "type": "stat",
     "description": "Number of worker nodes in cluster",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_node_labels{cluster=\"$Cluster\", label_kubernetes_io_role!=\"master\"})"
      }
     ]
    },
    {
     "title": "Nodes - KernelDeadlock",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"KernelDeadlock\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes - PIDPressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"PIDPressure\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes - MemoryPressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"MemoryPressure\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes - NetworkUnavailable",
     "type": "stat",
     "description": "NetworkUnavailable has Cilium/Calico as prerequisite - it is not working without it",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"NetworkUnavailable\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes - FrequentUnregisterNetDevice",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"FrequentUnregisterNetDevice\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes - DiskPressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"DiskPressure\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes - ReadonlyFilesystem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 1, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"ReadonlyFilesystem\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes - FrequentKubeletRestart",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"FrequentKubeletRestart\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes - FrequentDockerRestart",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"FrequentDockerRestart\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes - FrequentContainerdRestart",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"FrequentContainerdRestart\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes - CorruptDockerOverlay2",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 19, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=\"$Cluster\", condition=\"CorruptDockerOverlay2\", status=\"true\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Jobs - Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_job_status_succeeded{cluster=\"$Cluster\"} > 0) or vector(0)"
      }
     ]
    },
    {
     "title": "Jobs - Active",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_job_status_active{cluster=\"$Cluster\"} > 0) or vector(0)"
      }
     ]
    },
    {
     "title": "Jobs - Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_job_status_failed{cluster=\"$Cluster\"} > 0) or vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Deployments",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_deployment_status_replicas{cluster=\"$Cluster\"} > 0)"
      }
     ]
    },
    {
     "title": "Deployments - Replicas",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{cluster=\"$Cluster\"} > 0)"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{cluster=\"$Cluster\"} > 0)"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{cluster=\"$Cluster\"} > 0) or vector(0)"
      }
     ]
    },
    {
     "title": "Deployments - unavailable replicas",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_unavailable{cluster=\"$Cluster\"} > 0 or on() vector(-1)"
      }
     ]
    }
   ]
  },
  {
   "title": "DaemonSets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Daemonsets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_daemonset_status_number_ready{cluster=\"$Cluster\"} > 0)"
      }
     ]
    },
    {
     "title": "Daemonsets - Replicas",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_daemonset_status_desired_number_scheduled{cluster=\"$Cluster\"} > 0)"
      }
     ]
    },
    {
     "title": "Daemonsets Replicas - Unavailable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_daemonset_status_number_unavailable{cluster=\"$Cluster\"} > 0) or vector(0)"
      }
     ]
    },
    {
     "title": "Daemonsets Replicas - Misscheduled",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_daemonset_status_number_misscheduled{cluster=\"$Cluster\"} > 0) or vector(0)"
      }
     ]
    },
    {
     "title": "DaemonSets - unavailable replicas",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_daemonset_status_number_unavailable{cluster=\"$Cluster\"} > 0 or on() vector(-1)"
      }
     ]
    }
   ]
  },
  {
   "title": "StatefulSets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "StatefulSets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_statefulset_status_replicas{cluster=\"$Cluster\"} > 0)"
      }
     ]
    },
    {
     "title": "StatefulSets - Replicas",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_statefulset_status_replicas{cluster=\"$Cluster\"} > 0)"
      }
     ]
    },
    {
     "title": "StatefulSets Replicas - Updated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_statefulset_status_replicas_updated{cluster=\"$Cluster\"} > 0) or vector(0)"
      }
     ]
    },
    {
     "title": "StatefulSets Replicas - Unavailable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_statefulset_status_replicas{cluster=\"$Cluster\"} > 0) - sum(kube_statefulset_status_replicas_ready{cluster=\"$Cluster\"} > 0)"
      }
     ]
    },
    {
     "title": "StatefulSets - unavailable replicas",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(kube_statefulset_status_replicas{cluster=\"$Cluster\"} - kube_statefulset_status_replicas_ready{cluster=\"$Cluster\"}) > 0 or on() vector(-1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pods - Running phase",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Running\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"})"
      }
     ]
    },
    {
     "title": "Pods - Succeeded phase",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 5, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Succeeded\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Pods - Pending phase",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Pending\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Pods - Failed phase",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Failed\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Pods - Unknown phase",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{cluster=\"$Cluster\", phase=\"Unknown\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Pods - Ready state",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 2, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_ready{cluster=\"$Cluster\", condition=\"true\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Pods - Failed state",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_ready{cluster=\"$Cluster\", condition=\"false\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Pods - Unknown state",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_ready{cluster=\"$Cluster\", condition=\"unknown\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Pods - NotReady",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"} and on(pod) (kube_pod_container_status_ready{cluster=\"$Cluster\"} == 0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers - Ready",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_ready{cluster=\"$Cluster\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"})"
      }
     ]
    },
    {
     "title": "Containers - NotReady",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 5, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_ready{cluster=\"$Cluster\"} == 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Containers - Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_running{cluster=\"$Cluster\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"})"
      }
     ]
    },
    {
     "title": "Containers - NotRunning",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_running{cluster=\"$Cluster\"} == 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Containers - Terminated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 3, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_terminated{cluster=\"$Cluster\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Containers - Waiting",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_waiting{cluster=\"$Cluster\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Containers - Restarted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_restarts_total{cluster=\"$Cluster\"} > 0 and on(pod) kube_pod_info{cluster=\"$Cluster\", created_by_kind!=\"Job\"}) or vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers - Restarted",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(100, sort_desc(kube_pod_container_status_restarts_total{cluster=\"$Cluster\"} > 0))"
      }
     ]
    }
   ]
  }
 ]
}