{
 "title": "CoreDNS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CoreDNS Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$Cluster\"}[1m])) by (type)",
     "legendFormat": "Request {{ type }}"
    },
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$Cluster\"}[1m]))",
     "legendFormat": "Requests total"
    }
   ]
  },
  {
   "title": "Response Error codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{cluster=\"$Cluster\"}[1m])) by(zone,rcode)",
     "legendFormat": "{{ zone }} - {{ rcode }}"
    }
   ]
  },
  {
   "title": "CoreDNS Cache",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{cluster=\"$Cluster\"}[1m]))",
     "legendFormat": "Cache hits"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{cluster=\"$Cluster\"}[1m]))",
     "legendFormat": "Cache misses"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Forward latency",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(delta(coredns_forward_request_duration_seconds_bucket{cluster=\"$Cluster\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request latency all zones",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum(delta(coredns_dns_request_duration_seconds_bucket{cluster=\"$Cluster\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CoreDNS Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(coredns_cache_entries{cluster=\"$Cluster\"}) by (type)",
       "legendFormat": "Cache size - {{ type }}"
      }
     ]
    },
    {
     "title": "CoreDNS Cache split",
     "type": "timeseries",
     "description": "Split cache hits between positive(success) and negative(denial) cache.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(coredns_cache_hits_total{cluster=\"$Cluster\"}[1m])) by (type)",
       "legendFormat": "Cache hits - {{ type }}"
      }
     ]
    },
    {
     "title": "CoreDNS Cache forward/prefetch",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(coredns_cache_misses_total{cluster=\"$Cluster\"}[1m]))",
       "legendFormat": "Cache misses"
      },
      {
       "expr": "sum(delta(coredns_cache_prefetch_total{cluster=\"$Cluster\"}[1m]))",
       "legendFormat": "Cache prefetch"
      },
      {
       "expr": "sum(delta(coredns_forward_requests_total{cluster=\"$Cluster\"}[1m]))",
       "legendFormat": "Forwarded"
      }
     ]
    },
    {
     "title": "Stale cache entries serving rate",
     "type": "timeseries",
     "description": "Number of Stale entries served in 1m",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(coredns_cache_served_stale_total{cluster=\"$Cluster\"}[1m])) or on() vector(0)",
       "legendFormat": "stale items served"
      }
     ]
    }
   ]
  },
  {
   "title": "Forwarding stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Remote server rcodes",
     "type": "timeseries",
     "description": "Show remote server rcodes except noerror",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(coredns_forward_responses_total{cluster=\"$Cluster\", rcode!~\"NOERROR\"}[1m])) by (rcode,to)",
       "legendFormat": "{{to}} - {{rcode}}"
      },
      {}
     ]
    },
    {
     "title": "server zone reponse rcodes",
     "type": "timeseries",
     "description": "Show  server response rcodes per zone except noerror",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(coredns_dns_responses_total{cluster=\"$Cluster\"}[1m])) by(zone, rcode)",
       "legendFormat": "{{zone}} - {{rcode}}"
      },
      {}
     ]
    },
    {
     "title": "Forward healthcheck failure rate",
     "type": "timeseries",
     "description": "Remote endpoints forward healthcheck failure rate",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(coredns_forward_healthcheck_failures_total{cluster=\"$Cluster\"}[1m])) by (to) or on() vector(0)",
       "legendFormat": "{{ to }}"
      }
     ]
    },
    {
     "title": "Forward healthcheck broken rate",
     "type": "timeseries",
     "description": "Broken means all upstream down -> select upstream randomly",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(coredns_forward_healthcheck_broken_total{cluster=\"$Cluster\"}[1m])) by (to)",
       "legendFormat": "{{ to }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Replica sets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_replicaset_status_replicas{cluster=\"$Cluster\", replicaset=~\"$coredns.*\"}",
       "legendFormat": "{{ replicaset }}: Desired replicas"
      },
      {
       "expr": "kube_replicaset_status_ready_replicas{cluster=\"$Cluster\", replicaset=~\"coredns.*\"}",
       "legendFormat": "{{ replicaset }}: Ready replicas"
      }
     ]
    },
    {
     "title": "Total pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{cluster=\"$Cluster\", deployment=\"coredns\"})",
       "legendFormat": "Total pods"
      }
     ]
    },
    {
     "title": "Available pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{cluster=\"$Cluster\", deployment=\"coredns\"})",
       "legendFormat": "Available pods"
      }
     ]
    },
    {
     "title": "Unavailable pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_unavailable{cluster=\"$Cluster\", deployment=\"coredns\"}",
       "legendFormat": "Unavailable pods"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Container restarts",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "max(kube_pod_container_status_restarts_total{cluster=\"$Cluster\", pod=~\"coredns.*\"}) by (pod, container)",
       "legendFormat": "{{ pod }} - {{ container }}"
      }
     ]
    }
   ]
  }
 ]
}