{
 "title": "Kyverno ClusterPolicyReport Details",
 "tags": [
  "Kyverno",
  "Policy Reporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   },
   {
    "name": "policy",
    "label": "Policy",
    "query": {
     "query": "label_values(cluster_policy_report_result, policy)"
    }
   },
   {
    "name": "category",
    "label": "Category",
    "query": {
     "query": "label_values(cluster_policy_report_result, category)"
    }
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {
     "query": "label_values(cluster_policy_report_result, severity)"
    }
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": {
     "query": "label_values(cluster_policy_report_result, kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Policy Pass Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", status=\"pass\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Policy Warning Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", status=\"warn\"})"
    }
   ]
  },
  {
   "title": "Policy Fail Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", status=\"fail\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Policy Error Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", status=\"error\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Status Timeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", cluster=~\"$cluster\"} > 0) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Passed Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", status=\"pass\", cluster=~\"$cluster\"}) by (policy,rule,kind,name,status,severity,category,cluster)"
    }
   ]
  },
  {
   "title": "Failed Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", status=\"fail\", cluster=~\"$cluster\"}) by (policy,rule,kind,name,status,severity,category,cluster)"
    }
   ]
  }
 ]
}