apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    test: someupdate
    test2: someupdate3
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    securityContext:
      allowPrivilegeEscalation: true
---
apiVersion: apps/v1beta1
kind: Deployment
metadata: -1
spec:
  template:
    spec:
      containers:
      - name: myapp-container2
        image: busybox
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
        securityContext:
          allowPrivilegeEscalation: true
